// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewWarehouseAPI.Models;

namespace NewWarehouseAPI.Migrations
{
    [DbContext(typeof(GoodDetailContext))]
    partial class GoodDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewWarehouseAPI.Models.GoodDetail", b =>
                {
                    b.Property<int>("GoodDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GoodContractDate")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoodContractNum")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoodImage")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GoodName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoodQuantity")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoodUnits")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoodVendor")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GoodDetailId");

                    b.ToTable("GoodDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
